### ISSUE TITLE
How to I install the fork

### ISSUE THREAD

**Issue by kitterweed** [Skooz/XIVComboPlugin#10]
You wrote a message under an issues thread in the main plugin stating that we can download this to input it into dalamud but i cant for the life of me figure out how.

**Comment by kitterweed** [comment]
To clarify, I figured how to download, but I cant figure out how to upload it into dalamud

**Comment by kitterweed** [comment]
Disregard im only a bit dumb.

**Comment by Skooz** [comment]
Figured it out, then? Basically if you don't want to manually build the project yourself, you just download what I put in the "Releases" section.
