### ISSUE TITLE
[RDM] Change Acceleration to Grand Impact when active

### ISSUE THREAD

**Issue by MedicaExMachina** [Skooz/XIVComboPlugin#12]
What is thy suggestion?
Right now if you execute Acceleration while you have the other parts of the RDM settings enabled, they correctly don't update to Grand Impact. But keeping a single instance of Jolt III or Impact on your bars when they're already rolled into Verstone/Verfire or Veraero II/Veraero II seems counter to the aim of the mod, to reduce button bloat.

Therefore, my solution would be to change Acceleration to Grand Impact, much like Embolden and Manafication change to their combo abilities. Essentially: Hit Acceleration, it grants Grand Impact Ready, Acceleration button changes to Grand Impact until Grand Impact ready is used/lost, changes back to Acceleration.

1) Are abilities in question must be truly mutually exclusive?
The abilities in question are not mutually exclusive, so long as you're at the right level. 

2) Does this actually saves you button space?
Short of executing the game's logic and changing Jolt III or Impact itself (which are folded into other abilities in the plugin as it stands), yes.

3) Is it wild and wacky?
I wouldn't say so.

4) Is the overall level of intelligence required to execute is about as low as the floor?
I'd hope so. Big flashing button with blue flower on it to let you know that you have Grand Impact ready for cast shouldn't be too hard to see.

**Comment by Skooz** [comment]
Ah, this was something I missed in RDM. Oops.

What I need to do is make it so the existing combos account for the new condition. I'll get to work on that ASAP.

**Comment by Skooz** [comment]
Alright, it should be working now, though I can't actually test it. 

I need the buff ID for Grand Impact Ready, if you're able to get it. It should work fine in its current state, but I consider my implementation a bit sloppy for the time being. No worries if you don't know how.

**Comment by MedicaExMachina** [comment]
Okay! I think I have it.

The hex ID for it is 0xf25, and I believe the buff ID is 3877. I got these from Triggevent, first time using it so I'm hoping I'm right?

**Comment by Skooz** [comment]
Seems right. If you could test it out for me, here are the files.

[XIVComboDebug.zip](https://github.com/user-attachments/files/16180242/XIVComboDebug.zip)

**Comment by MedicaExMachina** [comment]
Works like a charm! I hit Acceleration and Grand Impact immediately shows up on all relevant buttons, whether I have Verstone/Verfire ready or not too.

**Comment by Skooz** [comment]
Goooood. I'll submit that change to the main repo as well. Thanks for the help!
