### ISSUE TITLE
[Issue] SCH: Adloquium Downgrade Breaks Seraphism

### ISSUE THREAD

**Issue by Daasanh** [Skooz/XIVComboPlugin#15]
When the Downgrade Adloquium to Physick option is selected, Adloquium does not change properly to Manifestation while under the effect of Seraphism.  Removing the combo option allows the ability change as intended.

![DownGrade-Adloq-Issue](https://github.com/user-attachments/assets/b3556523-8218-480c-8e92-b81233995b38)

![DownGrade-Adloq-Issue-B](https://github.com/user-attachments/assets/5dbb4938-7abb-411e-9841-256bf2cd70d2)

**Comment by Skooz** [comment]
Ahh, yeah, Manifestation is new, so I missed that. Technically, if I comment out the line to return Adloquium, it should work fine without causing any issues. Included files so you can test.

[XIVComboDebug.zip](https://github.com/user-attachments/files/16233963/XIVComboDebug.zip)

**Comment by Daasanh** [comment]
Confirmed issue is resolved.  Thankyou for working on this through the launch; some of the melee classes truly are nigh un-tenable without it.
