### ISSUE TITLE
[suggestion] Ability to split 1 from 2-B and 2-C combo options.

### ISSUE THREAD

**Issue by biomagnet** [Skooz/XIVComboPlugin#16]
Something simple for classes such as Samurai and Dragoon, where all combos start with 1, but branch off at 2 (as opposed to Warrior and Ninja which branch off at 3). aka the ability to have a 1 > 2-A > 3-A combo and another that starts at 2-B > 3-B for much more visually-distinct hotbars, rather than having *all* of them start with 1. I asked Attick in the past and he didn't seem against it but wanted to try something else and nothing came of it, but this would be for those with ADHD or memory issues, or trying to learn new muscle memory for lowering the button bloat. Like myself.

For example:
DRG
![image](https://github.com/user-attachments/assets/c2158a55-7667-4618-a570-7633a819ebbf) 
True Thrust/Raiden Thrust > Lance Barrage > Heaven's Thrust > Fang & Claw > Drakesbane > Raiden Thrust
Spiral Blow > Chaotic Spring > Wheeling Thrust > Drakesbane 
![image](https://github.com/user-attachments/assets/6a008172-fc7c-4ee8-ab20-99821a44fe5f) 
Lance Barrage > Heaven's Thrust > Fang & Claw > Drakesbane
True Thrust/Raiden Thrust > Spiral Blow > Chaotic Spring > Wheeling Thrust > Drakesbane > Raiden Thrust

SAM
![image](https://github.com/user-attachments/assets/c7a52351-8335-4df5-8b41-4ec738375a1a) into ![image](https://github.com/user-attachments/assets/84ca570e-0150-4f5d-9d93-c448089a8d76)

**Comment by Skooz** [comment]
I imagine attick only hesitated because there's currently a hard limit to how many combo options we can have in XIVCombo, lol. That's something that needs to be addressed, before options like these can be comfortably added.

Of course, you can always add it yourself. Wouldn't be all that hard either, as you can simply edit what's already there; just return Jinpu/Shifu instead of Hakaze, like so:

```c#
// Replace Gekko with Gekko combo
if (Configuration.ComboPresets.HasFlag(CustomComboPreset.SamuraiGekkoCombo))
    if (actionID == SAM.Gekko)
    {
        if (SearchBuffArray(SAM.BuffMeikyoShisui)) return SAM.Gekko;
        if (comboTime > 0)
        {
            if (lastMove == SAM.Jinpu && level >= 30) return SAM.Gekko;
        }

        return SAM.Jinpu;
    }

// Replace Kasha with Kasha combo
if (Configuration.ComboPresets.HasFlag(CustomComboPreset.SamuraiKashaCombo))
    if (actionID == SAM.Kasha)
    {
        if (SearchBuffArray(SAM.BuffMeikyoShisui)) return SAM.Kasha;
        if (comboTime > 0)
        {
            if (lastMove == SAM.Shifu && level >= 40) return SAM.Kasha;
        }

        return SAM.Shifu;
    }

```

**Comment by biomagnet** [comment]
I'm not too familiar with this sort of thing, but I'll take as best a look into it as I can. I appreciate the example to work with very very much! This could be a game-changer.

For what it's worth, I did find [my original suggestion](https://github.com/attickdoor/XIVComboPlugin/issues/70), too.

**Comment by biomagnet** [comment]
Hi! I'm trying this out with a friend of mine attempting to rebuild it. We're getting some errors building it (cannot find namespace Dalamud, etc.?) but seeing how we can work through those. In the meantime, does this look about correct for the Chaos Thrust combo?

```           // Replace Chaos Thrust with the Chaos Thrust combo chain
            if (Configuration.ComboPresets.HasFlag(CustomComboPreset.DragoonChaosThrustCombo))
                if (actionID == DRG.ChaosThrust || actionID == DRG.ChaoticSpring)
                {
                    if (comboTime > 0)
                    {
                        if ((lastMove == DRG.TrueThrust || lastMove == DRG.RaidenThrust) && level >= 18)
                        {
                            if (level >= 96)
                                return DRG.SpiralBlow;
                            if (level >= 18)
                                return DRG.Disembowel;
                        }
                        if (lastMove == DRG.Disembowel || lastMove == DRG.SpiralBlow)
                        {
                            if (level >= 86)
                                return DRG.ChaoticSpring;
                            if (level >= 50)
                                return DRG.ChaosThrust;
                        }
                        if ((lastMove == DRG.ChaosThrust || lastMove == DRG.ChaoticSpring) && level >= 58)
                            return DRG.WheelingThrust;
                        if ((lastMove == DRG.WheelingThrust) && level >= 64)
                            return DRG.Drakesbane;
                    }
                    
                            if (level >= 96)
                                return DRG.SpiralBlow;
                            if (level >= 18)
                                return DRG.Disembowel;
                }

**Comment by ProfBlack** [comment]
Friend here! 👋
Looks like the issue is that I need to install the game and Dalamud so I’m working on that now.

**Comment by Skooz** [comment]
Sounds like you're missing the Dalamud libraries. If you're building via Visual Studio Community, it should fetch the NuGet Dalamud package (and other dependencies) automatically.

Otherwise, at a glance, code looks alright. If there are any oddities, you'll be able to sort them out once you can build.

![image](https://github.com/user-attachments/assets/157bf227-a9f1-4847-ba9c-65b67de84fef)

**Comment by ProfBlack** [comment]
Looks like the DalamudPackager was already installed however this turned me onto fixing a few of my other missing dependencies. Still I seem to be missing a few.
![image](https://github.com/user-attachments/assets/eb56d776-b74b-444f-98e8-3e992b0a0e5e)

**Comment by ProfBlack** [comment]
![image](https://github.com/user-attachments/assets/d23c87f8-2b53-4dca-a882-8b4801de0f55)
My build errors btw.

**Comment by Skooz** [comment]
I was having that issue while working on my laptop. Seemed like it was just Visual Studio jank, and futzing around a bit fixed it. Think all I did was open the project properties and it seemed to suddenly remember where the dependencies were located.

**Comment by ProfBlack** [comment]
Ah interesting. I'll keep at it! I was seeing that https://github.com/goatcorp/SamplePlugin requires an installation of XIV and Dalamud. Would this be the same?

**Comment by Skooz** [comment]
It's totally possible. I've never worked with plugins on a machine that didn't have Dalamud\FFXIV installed, though those instructions may simply be implying that you need to have Dalamud+FFXIV to actually be able to test and use the plugin.

**Comment by ProfBlack** [comment]
That's a good thought. It's an hour away from finishing so I guess we'll see. I'm in no major rush and biomagnet is at work for 4 more hours yet. I very much appreciate your help!

**Comment by ProfBlack** [comment]
Success with the building after installing the game and XIV Launcher. Just gotta wait a few hours for @biomagnet to get home so he can test. Thank you so much for your help!

**Comment by biomagnet** [comment]
Success!! It's all worked exactly to plan. I sincerely appreciate that you helped us figure it out even though it was essentially a "do it yourself" project. Thanks so much!
