### ISSUE TITLE
Dev Plugins not working

### ISSUE THREAD

**Issue by Chaste-Alt** [Skooz/XIVComboPlugin#17]
I've found the dev plugin location, tried installing it as described and it's not working any ideas why that would be?

**Comment by Voide-github** [comment]
Your Experimental tab looks like this with the following files in the dir?
![image](https://github.com/user-attachments/assets/f2e11252-6b9b-4cda-83c1-ffa8f0aa780c)

I just reloaded the Dev Plugin to test and its definitely still working.   If you are using a directory that you previously removed, you will need to completely remove (hit the trashcan) and then re-add it, probably a mapped GUID or something. 

I'm not sure why, but I did notice that a lot of good updates from this branch didn't make it back into the main version (DRG combo, Heal downgrades, etc)  . I don't blame people for wanting to run an older dev version, its what I do.

**Comment by Skooz** [comment]
> (DRG combo, Heal downgrades, etc)

AFAIK DRG combo was unintentionally broken, while Heal downgrades are something attick doesn't want to do. Admittedly, it is a niche situation, and IIRC you can just go grab XIVSlothCombo for it if you really want to.
