### ISSUE TITLE
[Issue] Low level replace for WHM and AST gone

### ISSUE THREAD

**Issue by demonsdawn** [Skooz/XIVComboPlugin#18]
The option to replace benefic II and Cure II, for AST and WHM respectively, with their I version below level 30 seems to have disappeared from the new version.

This might be related to an earlier issue with SCH that was fixed by disabling the option.

**Comment by Skooz** [comment]
As intended. The recent release is based off the most recent version of the official plugin. Cure downgrades will never be added to the official version of the plugin, and I don't plan to support my own version of the plugin indefinitely.
