### ISSUE TITLE
[Suggestion] AST option - Minor Arcana on Draw

### ISSUE THREAD

**Issue by demonsdawn** [Skooz/XIVComboPlugin#19]
For AST would it be possible to have an option that replaces draw with minor arcana (when you have access to it)? 
It would have to be mutually exclusive with the other option, to prevent conflicts but both options effectively save 1 key.

As far as i can tell it aligns with Atticks guidlines, with the only caveats being:

1. Draw coming off cooldown before you use your minor arcana. This should however not be an issue as you'd lose this instance of minor arcana when you cast draw again, meaning you lose nothing, just have to press the button twice.
2. You accidentally press the button twice and re-draw all your cards which you for some reason did not use, like who does this anyway?

**Comment by Skooz** [comment]
I changed it to *just* Minor Arcana, because it's a bit silly to have it 4 times, or at least I think so. It's available in the latest release, albeit you'll have to be on the staging branch of Dalamud to get it to work.

https://github.com/Skooz/XIVComboPlugin/releases/tag/tweaks2

**Comment by demonsdawn** [comment]
Thanks for the quick response!
So far it appears the change does not work on pre-level 70 content. The minor arcanas get drawn as part of the draw action even if you do not have access to them, thus locking out the draw action at lower levels altogether.

likely have to force the swap at level 69 and below, additionally its locked behind the level 70 job quest.

**Comment by Skooz** [comment]
Interesting. That almost seems like sloppy coding on Square's part. 

Pushed a fix for it, and updated the zip. It'll keep Draw on Minor Arcana if you're under level 70 now.
