### ISSUE TITLE
Viper issue

### ISSUE THREAD

**Issue by Zamugustar** [Skooz/XIVComboPlugin#20]
So I know viper is a work in progress but it is ALMOST perfect. When you use Hunter's Coil, Swiftskin's Coil, Hunter's Den, or Swiftskin's Den they properly change to the proper Bite and Thresh move so you can leave Twinblood and Twinfang off the bar. Unfortunatly those two moves also become active when you use Uncoiled fury and transform into Uncoiled Twinfang and Uncoiled Twinblood, however when you use Uncoiled Fury nothing changes to those moves so you still have to have Twinblood and Twinfang on your bar. 

I suggest making the above listed 4 moves (Hunter's Coil, Swiftskin's Coil, Hunter's Den, or Swiftskin's Den) transform into Twinblood/Twinfang when you use uncoiled fury as well, assuming this is possible.

**Comment by Skooz** [comment]
When I uploaded it, I was still awaiting some updates from attick to be pushed to Dalamud's API. So, like you suggest, it was just a mostly functioning demo.

I've put up a new version that should work more reliably, and also shouldn't require twinfang\twinblood to be on your hotbar. Only catch is you'll have to be on the Staging branch of Dalamud for it to work, as the changes have not yet made their way to the Release build.

**Comment by Skooz** [comment]
Hmm... Maybe I misunderstood?

Uncoiled Fury's follow-ups (Uncoiled Twinfang/Twinblood) should've been appearing on the Uncoiled Fury button already. Though there may have been some weird code voodoo causing that to not work sometimes. Hopefully it works now.

**Comment by Zamugustar** [comment]
Yes tested, it works perfectly now. :)
