### ISSUE TITLE
SMN Lv92 ability

### ISSUE THREAD

**Issue by rickfert** [Skooz/XIVComboPlugin#21]
At level 92, Necrotize replaces Fester as the single target Aetherflow ability. In the XIVCombo settings it says to change Fester & Necrotize into Energy Drain when out of Aetherflow stacks. I had to drag Necrotize to the bar but it doesn't change to Fester in content under level 92. If I drag Fester to the bar, then it doesn't change to Necrotize in content above level 92.

**Comment by Skooz** [comment]
Seems the code was simply returning Fester and not Necrotize. Should be fixed now?

Files to test.
[XIVComboTweaks.zip](https://github.com/user-attachments/files/16530686/XIVComboTweaks.zip)

**Comment by rickfert** [comment]
Thank you. That fixed the issue.
