### ISSUE TITLE
RPR added new Skill to Enshrouded Combo

### ISSUE THREAD

**Issue by Scaco** [Skooz/XIVComboPlugin#4]
Hi,
first thanks for merging the Pull Requests.
I made an update for the Reaper to add the new skill "Perfectio" to the Enshrouded Combo. Wanted to create a Pull Request on the original Repository but failed.
If you want to add this in yours, feel free to do it.

CustomComboPreset.cs
changed Line 186: [CustomComboInfo("Enshroud Combo", "Replace Enshroud with Communio while you are Enshrouded and if Perfectio Parata is active it switch to Perfectio.", 39)] 
(Maybe not good english)

IconReplacer.cs
added new line
after Line 886: if (SearchBuffArray(RPR.Buffs.PerfectioParata) && level >= RPR.Levels.Perfectio) return RPR.Perfectio;

RPR.cs
added new Lines
after Line 17: Perfectio = 36973,
after Line 30 (Buff): PerfectioParata = 3860,
after Line 52 (Level): Perfectio = 100;

I tested it on top of your repository and it works fine.

**Comment by Skooz** [comment]
I'll try to add it when I get the chance, thanks!

In the future, you'd want to make your own fork of XIVCombo (seems like you don't have one?) to submit pull requests to the main repo. Clone your fork, make & push your changes to a separate branch on your fork, then submit a pull request to the main repo with your fork's branch. 

Just make sure you're only submitting **your** changes, if you create a pull request for the main repo.

**Comment by Skooz** [comment]
Implemented.

Changed some wording and logic. We don't need to check Reaper's level for Perfectio, as you can't get the Perfectio Parata status while under lvl 100 anyway.

**Comment by Scaco** [comment]
Thank you and i will look into fork on the weekend.
