### ISSUE TITLE
[PLD] Requiescat combo not updating after 96 >> Imperator

### ISSUE THREAD

**Issue by GoldenSunFelix** [Skooz/XIVComboPlugin#7]
Compiled the .sln and ran it, seems like once lvl 96 hits and Requiescat upgrades to Imperator it doesn't recognize the combo a la WAR's Inner Release to Primal Rend/Wrath/Ruination. Not trying to rush but thought PLD was in the update and wanted to make sure it was on radar. Still very new to using visual studio and C# so apologies if I missed something obvious.

**Comment by Skooz** [comment]
PLD was somebody's pull request, but I didn't take a close look at what they did. Some of the pull requests have been pretty sloppy, lol. 

Seems they forgot a check, and the combo was only applying to Requiescat, not Imperator (they're separate action IDs).

Fixed & pushed the change, so it should work now, but I can't test for myself. Let me know if there are any problems.
