### ISSUE TITLE
Noob troubleshooting question

### ISSUE THREAD

**Issue by kajsle** [Skooz/XIVComboPlugin#8]
Hi, noob with mods and with github here, sorry! 

I added the XIVComboPlugin-master folder path to Dev Plugin Locations (I hope that this is what I was supposed to do) but I am not sure how to access it now, as I still have the outdated version installed. Idk if it's supposed to be in the plugin list or there's another way to access settings. Help :)

**Comment by Tyndareus** [comment]
Needs to be the built project; either the release tags or an actual bin output from an IDE where the XIVCombo.dll is

**Comment by kajsle** [comment]
I am very sorry I don't know what any of that means :( Looks like I will have to wait for the official version, thank you anyways!

I was thinking it was easy when I read this lol

https://github.com/attickdoor/XIVComboPlugin/issues/293#issuecomment-2215959097

**Comment by kajsle** [comment]
sorry again, I realized I was adding the wrong folder / file. I got the debug version from here now, https://github.com/Skooz/XIVComboPlugin/releases and followed instructions and I am still not seeing it in my dalamud plugins list.

EDIT: I managed, sorry for the spam! <3

**Comment by Skooz** [comment]
All the files you see in the repositories are "unbuilt"; they're just project files. 

You can open the project via the `XIVCombo.sln` file, assuming you have Visual Studio installed. 
With the project open in VS, you can build the project\plugin, and the built files will be put in `\XIVComboPlugin\bin\Debug\`
That debug folder (assuming you built the project) is the directory you'd put into Dalamud as a dev plugin.

Just keep in mind, I have to manually build and update the "Releases" section myself, so sometimes recent fixes (like the PLD fix I just committed) won't be included right away, though I'll do my best to update it frequently.

**Comment by kajsle** [comment]
Thank you, I only play a few jobs atm, so I think this will work until the official update is released, it's a life saver. <3 I just tested the jobs I am using and they work fine ^^ And thank you for the explanation, I do have Visual Studio but my knowledge of the insides of xiv mods is non existent. Best leave it to the professionals xD Just having this work for me has made my week!

**Comment by Skooz** [comment]
Fortunately, you don't need to know anything about the code to build the project. Just open it up, right click the project in solution explorer, build, done! But hey, if everything you want already works anyway, then all's good. ❤️

If you do want to build yourself, just make sure you actually have **_Visual Studio_** and not **_Visual Studio Code_**. VS Code is like a modernized Notepad++, and building VS projects in there is like trying to bake a pizza with a toaster.

**Comment by kajsle** [comment]
Ahh good point, I do have VS Code and not the Visual Studio lol.. courtesy of casual Stardew modding xD Was wondering where the build button would be haha

Thank you again, I will have this info in mind in case of emergency <3
